### ISSUE TITLE
Installation trouble on Windows and Linux

### ISSUE THREAD

**Issue by incorpusyehtee** [Schlaefer/Saito#319]
Windows XAMPP with PHP 5.6.3, Linux with 5.5.9

I made a thread on the support forum, but I would appreciate any help getting past the install screen linking to a 404 page for the database configuration (my reply to that thread). The software looks great and I would love to run it!

http://saito.siezi.com/forum/entries/view/171

**Comment by Schlaefer** [comment]
I don’t have XAMPP at hand at the moment. But it comes down to getting CakePHP 2 to run on XAMPP.

Can you check that mod_rewrite is enabled [1]. This could be the reason for the 404 you see.

[1] Step 3 here: https://www.cometchat.com/blog/setup-cakephp-using-xampp-on-windows/
