### ISSUE TITLE
Show favicon-indicator about unread postings on background autoreload

### ISSUE THREAD

**Issue by iBook140** [Schlaefer/Saito#95]
Also to consider:
- quickly evaluate number of new entries in thread

**Comment by Schlaefer** [comment]
Wenn ich es richtig in Erinnerung habe, ging es darum, dass ein Hinweis im Tab-Favicon über neue Postings eingeblendet wurde. Szenario: man hat das Forum irgendwo in einem Tab offen - u.U. den Tab angepinnt - und Autoreload aktiviert. Dann möchte man sehen, wenn nach einem Autoreload im Hintergrund neue Postings vorhanden sind.
